# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BNWVuS45klHwmSkIVIO1qOZNHzF5nYR

# **Conversión de un audio MP3 a binario**

Se lee cada byte del audio y se convierte en su equivalente ASCII (integer). Posteriormente, se toman esos integers y se convierten a binario.
"""

mp3_ruta = 'audio.mp3'
txt_ruta = 'audio_binario.txt'

with open(mp3_ruta, 'rb') as mp3_file:
    with open(txt_ruta, 'w') as txt_file:
        byte = mp3_file.read(1) # lee cada byte

        while byte:
            binary_num = format(ord(byte), '08b') # ord() convierte a ASCII y format() convierte a binario
            txt_file.write(binary_num + '\n') # escribe en el txt y cambia de linea
            byte = mp3_file.read(1) # actualiza el byte a leer

print(f"Audio MP3 '{mp3_ruta}' escrito en '{txt_ruta}'")